version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: rehearsal
      POSTGRES_PASSWORD: rehearsal_pw
      POSTGRES_DB: rehearsal_db
    ports:
      - '5432:5432'
  backend:
    build: ./server
    environment:
      DB_HOST: db
      DB_USER: rehearsal
      DB_PASSWORD: rehearsal_pw
      DB_NAME: rehearsal_db
    depends_on:
      - db
    ports:
      - '5000:5000'
  frontend:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - backend